	$(document).ready(function(){
		 $(".One").hide();
		 $(".Two").hide();
		 $(".Three").hide();
		$(".Four").hide();
		$(".Five").hide();
		$(".Six").hide();
		$(".Seven").hide();
		$(".Eight").hide();
		$(".Nine").hide();
		$(".Ten").hide();
		 $("#collapseTen").click(function(){
      $(".Ten").slideToggle();
    });
		 $("#collapseNine").click(function(){
      $(".Nine").slideToggle();
    });
		 $("#collapseEight").click(function(){
      $(".Eight").slideToggle();
    });
		 $("#collapseSeven").click(function(){
      $(".Seven").slideToggle();
    });
		 $("#collapseSix").click(function(){
      $(".Six").slideToggle();
    });
		 $("#collapseFive").click(function(){
      $(".Five").slideToggle();
    });
     $("#collapseFour").click(function(){
      $(".Four").slideToggle();
    });
		 $("#collapseThree").click(function(){
      $(".Three").slideToggle();
    });
		 $("#collapseTwo").click(function(){
      $(".Two").slideToggle();
    });
		 $("#collapseOne").click(function(){
      $(".One").slideToggle();
    });
  });
